import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../app/globals.css";
import { wrapper } from "@/store";
import { Provider } from "react-redux";
import { AppProps } from "next/app";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
import { SnackbarProvider } from "notistack";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function MyApp({
  Component,
  ...rest
}: AppProps<{ isAuthPage: boolean; isProtected: boolean }>) {
  const { store, props } = wrapper.useWrappedStore(rest);
  const { pageProps } = props;

  return (
    <>
      <Provider store={store}>
        <AuthProvider pageProps={pageProps}>
          <SnackbarProvider autoHideDuration={1500}>
            <div className={``}>
              <Component {...pageProps} />
            </div>
          </SnackbarProvider>
        </AuthProvider>
      </Provider>
    </>
  );
}

export default MyApp;
